@baseUrl = http://localhost:5000
@urlPath = api/v1

###
POST {{baseUrl}}/{{urlPath}}/signup
Content-Type: application/json
Accept: application/json

{
  "mobileNumber": "+2348088866150",
  "password": "promise",
  "firstname": "Promise",
  "lastname": "Sheggsmann",
  "otpProvider": "sms"
}



###
PUT {{baseUrl}}/{{urlPath}}/verify-account
Content-Type: application/json
Accept: application/json

{
  "mobileNumber": "+2348088866150",
  "otp": "2650"
}



###
POST {{baseUrl}}/{{urlPath}}/validate-number
Content-Type: application/json
Accept: application/json

{
  "mobileNumber": "+2348088866150"
}



###
POST {{baseUrl}}/{{urlPath}}/resend-otp
Content-Type: application/json
Accept: application/json

{
  "mobileNumber": "+2348088866150",
  "otpProvider": "sms"
}



###
POST {{baseUrl}}/{{urlPath}}/signin
Content-Type: application/json
Accept: application/json

{
  "mobileNumber": "+2348088866150",
  "password": "promise"
}



###
POST {{baseUrl}}/{{urlPath}}/forgot-password
Content-Type: application/json
Accept: application/json

{
  "mobileNumber": "+2348088866150",
  "otpProvider": "sms"
}



###
POST {{baseUrl}}/{{urlPath}}/reset-password
Content-Type: application/json
Accept: application/json

{
  "mobileNumber": "+2348088866150",
  "otp": "5356",
  "password": "promise",
  "confirmPassword": "promise"
}
