@baseUrl = http://localhost:5000
@urlPath = api/v1

###
POST {{baseUrl}}/{{urlPath}}/signup
Content-Type: application/json
Accept: application/json

{
  "mobileNumber": "+2348088866150",
  "password": "promise",
  "firstname": "Promise",
  "lastname": "Sheggsmann",
  "otpProvider": "sms"
}

###
POST {{baseUrl}}/{{urlPath}}/signup
Content-Type: application/json
Accept: application/json

{
  "mobileNumber": "+2348147663563",
  "password": "promise",
  "firstname": "Nwokeji",
  "lastname": "Christian",
  "otpProvider": "sms"
}

###
POST {{baseUrl}}/{{urlPath}}/signup
Content-Type: application/json
Accept: application/json

{
  "mobileNumber": "+2348147663564",
  "password": "promise",
  "firstname": "Tristan",
  "lastname": "Tate",
  "otpProvider": "sms"
}


###
PUT {{baseUrl}}/{{urlPath}}/verify-account
Content-Type: application/json
Accept: application/json

{
  "mobileNumber": "+2348088866150",
  "otp": "0089"
}

###
PUT {{baseUrl}}/{{urlPath}}/verify-account
Content-Type: application/json
Accept: application/json

{
  "mobileNumber": "+2348147663564",
  "otp": "4370"
}


###
POST {{baseUrl}}/{{urlPath}}/validate-number
Content-Type: application/json
Accept: application/json

{
  "mobileNumber": "+2348088866150"
}



###
POST {{baseUrl}}/{{urlPath}}/resend-otp
Content-Type: application/json
Accept: application/json

{
  "mobileNumber": "+2348088866150",
  "otpProvider": "sms"
}

###
POST {{baseUrl}}/{{urlPath}}/resend-otp
Content-Type: application/json
Accept: application/json

{
  "mobileNumber": "+2348147663563",
  "otpProvider": "sms"
}



###
POST {{baseUrl}}/{{urlPath}}/store-signin
Content-Type: application/json
Accept: application/json

{
  "mobileNumber": "+2348088866150",
  "password": "promise"
}

###
POST {{baseUrl}}/{{urlPath}}/signin
Content-Type: application/json
Accept: application/json

{
  "mobileNumber": "+2348147663563",
  "password": "promise"
}

###
POST {{baseUrl}}/{{urlPath}}/signin
Content-Type: application/json
Accept: application/json

{
  "mobileNumber": "+2348147663564",
  "password": "promise"
}



###
POST {{baseUrl}}/{{urlPath}}/forgot-password
Content-Type: application/json
Accept: application/json

{
  "mobileNumber": "+2348088866150",
  "otpProvider": "sms"
}



###
POST {{baseUrl}}/{{urlPath}}/reset-password
Content-Type: application/json
Accept: application/json

{
  "mobileNumber": "+2348088866150",
  "otp": "5356",
  "password": "promise",
  "confirmPassword": "promise"
}
